### ISSUE TITLE
'S006e' missing from Dataset 1.

### ISSUE THREAD

**Issue by lol** [MAMEM/ssvep-eeg-processing-toolbox#55]
First of all thanks for providing this wonderful toolbox.

File 'S006e.mat' is missing from Dataset 1. Can you kindly update the archives on https://dx.doi.org/10.6084/m9.figshare.2068677

Many thanks.

**Comment by liarosge** [comment]
Hi,

Thanks for the observation, we will try to update it as soon as possible. In the meantime you may download the missing file from this [link](https://drive.google.com/file/d/0B78CJrM6Fga_bElxMlhJZWI5eTQ/view?usp=sharing)

**Comment by lol** [comment]
Thank you for the swift response. :)
